Repository DisnakeDev/guide, pull requests merged in 2022-03, with the labels that each got.

#33 feat(web): Update to the latest Docusaurus version. (2.0.0-beta.17)
  .github/workflows/lint-build-deploy.yml
  guide/docusaurus.config.js
  guide/package-lock.json
  guide/package.json
  guide/src/css/extraComponents.css
  guide/src/theme/MDXComponents/index.js
  guide/src/theme/MDXPage/index.js
  guide/src/theme/SearchPage/index.d.ts
  guide/src/theme/SearchPage/index.js
  guide/src/theme/SearchPage/styles.module.css
Labels: t: version update, s: needs review

#35 feat(web): Use Sass for CSS with `docusaurus-plugin-sass`.
  guide/docusaurus.config.js
  guide/package-lock.json
  guide/package.json
  guide/src/css/darkTheme.css
  guide/src/css/extraComponents.css
  guide/src/css/lightTheme.css
  guide/src/styles/_layout.scss
  guide/src/styles/_navbar.scss
  guide/src/styles/_search.scss
  guide/src/styles/_variables.scss
  guide/src/styles/index.scss
Labels: t: enhancement, s: needs review

#30 feat: add message content intent faq
  guide/docs/popular-topics/intents.mdx
Labels: t: enhancement, s: in progress
